services:
  # Backend Web Service
  - type: web
    name: portfolio-backend-n-hariprasath
    runtime: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://portfolio-frontend-n-hariprasath.onrender.com
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false

  # Frontend Static Site
  - type: web
    name: portfolio-frontend-n-hariprasath
    runtime: static
    staticPublishPath: frontend
